### PR TITLE
Add Hashable instances

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by ekmett** [comment]
Mind if we guard this with a MIN_VERSION_hashable check and a -fhashable option that defaults to on like I do with most of my other dependencies in low level packages?

**Comment by phadej** [comment]
Added `hashable` flag (copied the approach from `tagged`). Yet `vector-instances` depend on `hashable` through e.g. `pointed` anyway.

**Comment by ekmett** [comment]
Good point, though I'll likely go back and add a ton of flags to `pointed` at some point.

**Comment by ekmett** [comment]
I've added the flags to `pointed` HEAD, but not yet tested them

**Pull request merged**
